### PR TITLE
Malkab fixings and new version

### PR DESCRIPTION
**Pull request by malkab**
Fixed restarting issue, finished last version Awkward Aardvark tag, warning that all other tags are deprecated, added GeoJSON support, reenabled GDAL for CREATE EXTENSION postgis support, added more tests to usage cases folder.

### CODE REVIEW

**Comment by malkab** [comment]
@alasarr, @cayetanobv, check this. Please comment, merge if you see fit, and keep me inform about the CI procedure, would you?

**Comment by cayetanobv** [comment]
Compiled and tested locally. LGTM @malkab 
What do you think about this new tag system @alasarr ? If you are agree you can merge this PR.
Anyway without SFCGAL compile time and image size have been greatly reduced:

```
REPOSITORY                    TAG                                                 IMAGE ID            CREATED             SIZE
geographica/postgis           awkward_aardvark                                    aed0924f8907        8 minutes ago       1.002 GB
geographica/postgis           PostgreSQL-9.4.5-PostGIS-2.2.0-GDAL-2.0.1-Patched   15b994e39799        2 days ago          799.9 MB
geographica/postgis           postgresql-9.5.0-postgis-2.2.1-gdal-2.0.2-patched   8fb76f8889f1        2 days ago          1.282 GB
```

**Comment by malkab** [comment]
Ok @cayetanobv. Waiting for you to merge the pull request to trash this branch.

**Comment by alasarr** [comment]
I agree! Let's docker hub start working

**Comment by alasarr** [comment]
I'll close de issue as soon as Docker hub build the image

**Comment by alasarr** [comment]
Image available at docker hub: 

https://hub.docker.com/r/geographica/postgis/
https://hub.docker.com/r/geographica/postgis/tags/

**Pull request merged**
